// <auto-generated />
namespace Working.Infstructure.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _12 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_12));
        
        string IMigrationMetadata.Id
        {
            get { return "201612211958474_1.2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
